### ISSUE TITLE
Add a 's' to download filenames

### ISSUE THREAD

**Issue by costales** [gusbemacbe/suru-plus-folders#18]
Hi,

First, thanks for the icons!! :)

For working better with Folder Color extension ([readme](https://bazaar.launchpad.net/~costales/folder-color/trunk/view/281/README)), you should add a 's' to the [filenames here](https://github.com/gusbemacbe/suru-plus-folders/tree/master/images).

For example, folder-blue-download.svg should be folder-blue-download**s**.svg

A hug.

**Comment by gusbemacbe** [comment]
Hola @costales !

¡Discúlpame por mi ausencia! Yo estaba trabajando mucho con rel repositorio [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu), pero he terminado el trabajo y lanzado la nueva versión.

Acabo de actualizar el repositorio ahora. Ve se está bien. 

Como he terminado el proyecto, hoy debo hacer Suru++ Folder compatible con Suru++ Ubuntu.

**Comment by costales** [comment]
¡Hola!
Muchísimas gracias por el commit
Un abrazo y gracias de nuevo por estos iconos.
--
Costales.

**Comment by gusbemacbe** [comment]
De nada!
