### ISSUE TITLE
Suru++ 25 and Suru++ Ubuntu places folders use the different folders names

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus-folders#21]
Hello @SmartFinn!

Suru++ 25 uses the folder `64`, but Suru++ Ubuntu uses the folder `scalable`. Is it possible to use both `64` and `scalable` in these scripts?

**Comment by gusbemacbe** [comment]
Or I have to use only one of them @SmartFinn?

**Comment by gusbemacbe** [comment]
Hi @SmartFinn, as you can not help, I will have to rename all my folders from `64` to `scalable`, as Andrea wants to keep "scalable". Thank you!

**Comment by SmartFinn** [comment]
That is the best option because I don’t know how to teach the script to work with both themes.
