### ISSUE TITLE
color doesn't change .

### ISSUE THREAD

**Issue by Abdelwahab07** [gusbemacbe/suru-plus-folders#25]
Hi,
I used suru-plus-folders to change folder colors with this commands 
```
$ sudo suru-plus-folders -C blue --theme Suru++-Ubuntu
suru-plus-folders: Changing color of folders to 'blue' for 'Suru++-Ubuntu' ...
gtk-update-icon-cache: The generated cache was invalid.
```
then nothing changed and color still orange "default" ,
When i checked with :
`suru-plus-folders -l --theme Suru++-Ubuntu`

```
List of available colors:

   aubergine
 > blue
   bordeaux
   canonical
   cyan
   darkblue
   green
   orange
   purple
   red
   vermillion
   yellow

```
so what is the problem here  ?

**Comment by SmartFinn** [comment]
The color was actually changed, but cache generating is failed. The issue should be related to Suru++ Ubuntu. Maybe the theme has icons with an invalid name, again.

**Comment by SmartFinn** [comment]
Yep, the following icons have invalid charset in name:

```sh
 $ > LC_ALL=C find Suru++-Ubuntu/ -not -iregex '[-_/\.+@a-z0-9]+' -print
Suru++-Ubuntu/apps/16/propriet??-di-applicazione.svg
Suru++-Ubuntu/apps/scalable/propriet??-di-applicazione.svg
Suru++-Ubuntu/apps/symbolic/propriet??-di-applicazione-symbolic.svg
```

**Comment by Abdelwahab07** [comment]
Thanks, it worked.
