### ISSUE TITLE
syntax error on installer

### ISSUE THREAD

**Issue by VentGrey** [gusbemacbe/suru-plus-folders#30]
Running the quick install script located in the web page results in an error:

`sh: 1: Syntax error: "|" unexpected`

trying to replace `sh` with `bash` doesn't load the script either.

**Comment by SmartFinn** [comment]
@gusbemacbe That's happened because of \` symbol in the banner. Replace \` with \\` or better with other safe symbols.

**Comment by gusbemacbe** [comment]
@VentGrey and @SmartFinn, which one of three files?

**Comment by SmartFinn** [comment]
@gusbemacbe https://github.com/gusbemacbe/suru-plus-folders/blob/main/install.sh#L21

**Comment by gusbemacbe** [comment]
Done. Please, @VentGrey, test.

**Comment by VentGrey** [comment]
Everything now works :D
